[build]
  command = "pnpm install && CI=false pnpm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"
  NETLIFY_USE_PNPM = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
